### ISSUE TITLE
Can not connect to minecraft server

### ISSUE THREAD

**Issue by rlelecque** [drunner/minecraft#1]
Steps to reproduce:
Configure the minecraft port following the steps

What you expected to see:
The port to be configured correctly

What you saw instead
Permission is denied to /data/eula.txt.
Following the server is allowed to start following this, but users can not connect

**Comment by j842** [comment]
Should be okay now. You'll need to do:
drunner update
drunner update minecraft

(assuming your minecraft dService is called minecraft).

**Comment by rlelecque** [comment]
This is still not working after updating to the latest changes.
